---
hkcam_version: 'v0.0.9'
hkcam_download_file_name: hkcam-{{ hkcam_version }}_linux_armhf.tar.gz
hkcam_download_url: https://github.com/brutella/hkcam/releases/download/{{ hkcam_version }}/{{ hkcam_download_file_name }}
hkcam_download_dir: /tmp
hkcam_download_dest: "{{ hkcam_download_dir }}/{{ hkcam_download_file_name }}"
hkcam_data_dir: /var/lib/hkcam/data

disable_camera_led: false